name: 🛸 HTTPx | Screenshot 📷 
# This will likely increase as Repo Size gets bigger over time
#MAX_RUNTIME: 30-45 Mins
on:
  workflow_dispatch: # Whenever manually run from actions-tab
  schedule:
    - cron: "15 23 * * *" #( 11:15 PM UTC --> 05:00 AM Morning )
#------------------------------------------------------------------------------------#
jobs:
  Parse:
    runs-on: ubuntu-latest
    #timeout-minutes: 45 # Can't afford to finish the 2000 Minutes quotes    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main  

      - name: Install Coreutils
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          sudo apt update -y
          sudo apt install coreutils curl dos2unix fdupes jq moreutils wget -y
          # Again just because
          sudo apt install coreutils curl dos2unix fdupes jq moreutils wget -y
        continue-on-error: true

      - name: Install eget
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          # eget for bins
          sudo wget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/eget" -O "/usr/local/bin/eget"
          sudo chmod +xwr "/usr/local/bin/eget"
        continue-on-error: false

      - name: Install Deps
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #anew
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/anew" --to "/usr/local/bin/anew"
          #asn
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/asn" --to "/usr/local/bin/asn"
          #asnmap
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/asnmap" --to "/usr/local/bin/asnmap"
          #cut-cdn
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/cut-cdn" --to "/usr/local/bin/cut-cdn"          
          # dirstat-rs for tree
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/ds" --to "/usr/local/bin/ds"          
          #dnsx
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/dnsx" --to "/usr/local/bin/dnsx"
          #HTTPx
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/httpx" --to "/usr/local/bin/httpx"
          #gowitness
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/gowitness" --to "/usr/local/bin/gowitness"
          #inscope
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/inscope" --to "/usr/local/bin/inscope"
          #mapcidr
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/mapcidr" --to "/usr/local/bin/mapcidr"
          #scopegen
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/scopegen" --to "/usr/local/bin/scopegen"
          #scopeview
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/scopeview" --to "/usr/local/bin/scopeview"
          #spk
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/spk" --to "/usr/local/bin/spk"
          #yq
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/yq" --to "/usr/local/bin/yq"
        continue-on-error: true

      - name: Run
        run: |
          # Presets
          set -x ; set +e
          #Dos2unix
          dos2unix "$GITHUB_WORKSPACE/main/.github/scripts/scrape_certs_certstream_httpx_gowitness.sh"
          #chmod
          chmod +xwr "$GITHUB_WORKSPACE/main/.github/scripts/scrape_certs_certstream_httpx_gowitness.sh"
          #Run
          bash "$GITHUB_WORKSPACE/main/.github/scripts/scrape_certs_certstream_httpx_gowitness.sh"
        continue-on-error: true

      - name: Get DateTime
        run: |
          # Date Time
          NEPALI_TIME=$(TZ='Asia/Kathmandu' date +'%Y-%m-%d (%I:%M:%S %p)')
          echo "NEPALI_TIME=$NEPALI_TIME" >> $GITHUB_ENV
        continue-on-error: true

      - name: Git Pull
        run: |
           cd "$GITHUB_WORKSPACE/main" && git pull origin main
        continue-on-error: true
        
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main        
          commit_user_name: Azathothas # defaults to "github-actions[bot]"
          commit_user_email: AjamX101@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "✅ 🛸 HTTPx | Screenshot 📷 <-- ${{ env.NEPALI_TIME }} ⌚"
          push_options: '--force'
